title: Narwhal Audio
description: Open-source audio plugins and hardware.
remote_theme: "pmarsceill/just-the-docs"

url: https://NarwhalAudio.github.io

# Aux links for the upper right navigation
aux_links:
  "View Narwhal Audio on GitHub":
    - "https://github.com/NarwhalAudio"
  "Donate on Ko-Fi":
    - "https://ko-fi.com/ApolloFops"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
